-  name: disable the default version of nodejs
   ansible.builtin.shell: dnf module disable nodejs -y

-  name: enable nodejs18 version
   ansible.builtin.shell: dnf module enable nodejs -y


-  name: install nodejs
   ansible.builtin.dnf:
     name: nodejs
     state: installed

-  name: configure the backend service
   ansible.builtin.template:
     src: backend.service
     dest: /etc/systemd/system/backend.service

-  name: adding application user
   ansible.builtin.user:
     name: expense

-  name: app pre_requisites
   ansible.builtin.include_role:
     name: common
     tasks_from: app_prereq

-  name: download dependencies
   community.general.npm:
     path: /app

-  name: reloading systemd and start backend service
   ansible.builtin.systemd_service:
     name: backend
     state: started
     enabled: yes


-  name: install mysql client and python library for mysql
   ansible.builtin.dnf:
     name: "{{ item }}"
     state: installed
   loop:
     - mysql
     - python3-PyMySQL


-  name: load schema
   community.mysql.mysql_db:
     state: import
     name: all
     target: /app/schema/backend.sql
     login_user: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.expense.rds.username', region='us-east-1' ) }}"
     login_password: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.expense.rds.password', region='us-east-1' ) }}"
     login_host: "{{ lookup('amazon.aws.aws_ssm', 'dev.expense.rds.endpoint', region='us-east-1' ) }}"
