-  name: install nginx
   ansible.builtin.dnf:
     name: nginx
     state: installed


-  name: Copy the expense configuration file
   ansible.builtin.copy:
     src: expense.conf
     dest: /etc/nginx/default.d/expense.conf


-  name: app_prereqisites
   ansible.builtin.include.role:
     name: common
     tasks_from: app_prereq

- name: enable and start nginx service
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: restarted
