-  name: install nginx
   ansible.builtin.dnf:
     name: nginx
     state: installed


-  name: Copy the expense configuration file
   ansible.builtin.copy:
     src: expense.conf
     dest: /etc/nginx/default.d/expense.conf


- name: delete existing app content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download and extract app content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: enable and start nginx service
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: restarted
