format_version: 10
pipelines:
  deploy:
    group: defaultGroup
    label_template: "${COUNT}"
    lock_behavior: none
    display_order: -1
    materials:
      ansible:
        git: https://github.com/madhan-46/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments: ["-i", "frontend-dev.madhanmohanreddy.tech,", "-e", "ansible_user=centos", "-e", "ansible_password=DevOps321", "expense.yml"]





      - QA:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - -l
                      - - A





      - UAT:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - -l
                      - - A



      - PROD:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - -l
                      - - A