-  name: removing existing app content
   ansible.builtin.file:
     path: "{{ app_location }}"
     state: absent

-  name: create application directory
   ansible.builtin.file:
     path: "{{ app_location }}"
     state: directory
     owner: "{{app_user}}"


-  name: download and extract app content from artifactory
   ansible.builtin.unarchive:
     src: https://{{artifactory_user}}:{{artifactory_password}}@artifactory-internal.madhanmohanreddy.tech:8081/artifactory/expense-{{ component }}/{{app_version}}.zip
     dest: "{{ app_location }}"
     remote_src: true