-  name: Extract node exporter
   ansible.builtin.unarchive:
     src: https://github.com/prometheus/node_exporter/releases/download/v{{node_exporter_version}}/node_exporter-{{node_exporter_version}}.linux-amd64.tar.gz
     dest: /opt
     remote_src: yes

-  name: copy node exporter service
   ansible.builtin.template:
     src: node_exporter.service
     dest: /etc/systemd/system/node_exporter.service


-  name: copy the elastic repo file
   ansible.builtin.template:
     src: elastic.repo
     dest: /etc/yum.repos.d/elastic.repo


-  name: start node exporter
   ansible.builtin.systemd_service:
     name: node_exporter
     state: restarted
     enabled: yes
     daemon_reload: yes


-  name: install filebeat
   ansible.builtin.dnf:
     name: filebeat
     state: installed


-  name: filebeat config update
   ansible.builtin.template:
     src: filebeat.yml
     dest: /etc/filebeat/filebeat.yml


-  name: start filebeat
   ansible.builtin.systemd_service:
     name: filebeat
     state: restarted


-  name: configure syslog
   ansible.builtin.template:
     src: rsyslog.conf
     dest: /etc/rsyslog.d/{{component}}.conf


-  name: restart rsyslog
   ansible.builtin.systemd_service:
     name: rsyslog
     state: restarted